config/routes.rb
Rails.application.routes.draw do
   resources :posts do
      resources :comments
   end
   match 'remote_sign_up', to: 'remote_content#remote_sign_up', via: [:get]
   match 'remote_sign_in', to: 'remote_content#remote_sign_in', via: [:get]

   devise_for :users, :controllers => {registrations: 'registrations', sessions: 'sessions'}

   root "posts#index"

end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  comment    :text
#  post_id    :integer
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  validates :comment, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
   before_action :set_comment, only: [:show, :edit, :update, :destroy]
   before_action :authenticate_user!,  except: [:create]



   # GET /comments/1/edit
   def edit
      @post = Post.find(params[:post_id])
      @comment = @post.comments.find(params[:id])
   end

   # POST /comments
   # POST /comments.json
   def create
      if user_signed_in? 
         @post = Post.find(params[:post_id])
         @comment = @post.comments.new(comment_params)
         @comment.user_id = current_user.id if current_user
         respond_to do |format|
            if @comment.save
               flash.now[:success] = 'Comment was successfully created.'
               format.html { redirect_to post_path(@post)}
               format.js{}
            else
               format.html { render :new }
               format.js {
                  flash.now[:error] = @comment.errors.full_messages.to_sentence
                  
               }
            end
         end
      else
         redirect_to  remote_sign_in_path and return
      end


   end

   # PATCH/PUT /comments/1
   # PATCH/PUT /comments/1.json
   def update
      @post = Post.find(params[:post_id])
      @comment = @post.comments.find(params[:id])

      respond_to do |format|
         if @comment.update(comment_params)
            flash.now[:success] =  'Comment was successfully updated.'
            format.html { redirect_to post_path(@post) }
            format.js {}
         else
            flash.now[:notice] = "Comment could not be update" 
            format.html { render :edit }
            format.js {}
         end
      end
   end

   # DELETE /comments/1
   # DELETE /comments/1.json
   def destroy
      @post = Post.find(params[:post_id])
      @comment = @post.comments.find(params[:id])

      @comment.destroy
      respond_to do |format|
         flash.now[:info] = 'Comment was successfully destroyed.'
         format.html { redirect_to post_path(@post) }
         format.js # JavaScript response
      end
   end

   private
   # Use callbacks to share common setup or constraints between actions.
   def set_comment
      @comment = Comment.find(params[:id])
   end

   # Never trust parameters from the scary internet, only allow the white list through.
   def comment_params
      params.require(:comment).permit(:comment)
   end
end

app/views/comments/_comment.html.haml
.comment{:id => "#{dom_id(comment)}"}
  .content
    %p.comment_content= comment.comment
    %p.comment_author=  comment.user.email
    - if user_signed_in?
      .buttons.btn-group.btn-group-xs
        = link_to 'Edit', edit_post_comment_path(comment.post, comment),  remote: true, class: "btn btn-default"
        = link_to "Delete", post_comment_path(comment.post, comment), method: :delete, data: { confirm: "Delete comment?" }, remote: true, class: "btn btn-default"

app/views/comments/_form.html.haml
= simple_form_for([@post, @post.comments.build],  remote: true) do |f|
  = f.error_notification

  .form-inputs
    = f.input :comment

  .form-actions
    = f.button :submit

app/views/comments/_modal_form.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %button.close{"data-dismiss" => "modal" }
        %span ×
      %h4.modal-title 
        =action_name.capitalize 
        Comment

    .modal-body
      = simple_form_for( [@post, @comment], remote: true) do |f|
        = f.error_notification
        .form-inputs
          = f.input :comment
        .form-actions
          = f.button :submit

app/views/comments/create.js.erb
<%  unless @comment.errors.any?  %>
$( '<%= j(render @comment) %>' ).hide().insertBefore($('#comment_form_header').last()).show( "slow" );
$('#comments > h2').html('This article has <%= escape_javascript(pluralize(@post.comments.count, 'comment')) %>');
$("#new_comment").trigger('reset');
<% end  %>

<%= render 'notification', formats: [:js] %>

app/views/comments/edit.html.haml
%h1 Edit Reply

= simple_form_for([@post, @comment]) do |f|
  = f.error_notification

  .form-inputs
    = f.input :comment

  .form-actions
    = f.button :submit

= link_to 'Back', post_path(@post)

app/views/comments/edit.js.erb
$("#modal-window").html("<%= escape_javascript(render 'modal_form') %>")
$("#modal-window").modal("show")

app/views/comments/new.html.haml
%h1 New comment

= render 'form'

= link_to 'Back', comments_path

app/views/comments/update.js.erb
<%  unless @comment.errors.any?  %>
$("#modal-window").modal("hide")
$("#comment_<%= @comment.id %>").replaceWith("<%= escape_javascript(render partial: 'comment', locals: { comment: @comment } ) %>"); 

var el = $("#comment_<%= @comment.id %> .comment_content");
   el.before("<div/>")
   el.prev()
   .width(el.width())
.height(el.height())
   .css({
      "position": "absolute",
      "background-color": "#ffff99",
      "opacity": ".9"   
   })
.fadeOut(500);
<% end  %>


<%= render 'notification', formats: [:js] %>