config/routes.rb
Rails.application.routes.draw do
   resources :posts do
      resources :comments
   end
   match 'remote_sign_up', to: 'remote_content#remote_sign_up', via: [:get]
   match 'remote_sign_in', to: 'remote_content#remote_sign_in', via: [:get]

   devise_for :users, :controllers => {registrations: 'registrations', sessions: 'sessions'}

   root "posts#index"

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string
#  content    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class Post < ActiveRecord::Base
   belongs_to :user
   has_many   :comments
   validates  :title, presence: true
   validates  :content, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
     @posts = Post.all.order("created_at DESC")
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
     @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        flash.now[:success] = "Post was successfully created."
        format.html { redirect_to @post}
        format.js {}
      else
        format.html { render :new }
        format.js {}
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        flash.now[:success] = 'Post was successfully updated.'
        format.html { redirect_to @post }
        format.js {}
      else
        format.html { render :edit }
        format.js {}
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      flash.now[:info] = "Post was successfully destroyed."
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed'}
      format.js{} # JavaScript response
      
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/views/posts/_form.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %button.close{"data-dismiss" => "modal" }
        %span ×
      %h4.modal-title 
        =action_name.capitalize 
        Todo List

    .modal-body
      = simple_form_for @post, remote: true do |f|
        = f.error_notification
        .form-inputs
          = f.input :title
        .form-inputs
          = f.input :content, :as => :text, :input_html => { 'rows' => 6}
        .form-actions
          = f.button :submit

app/views/posts/_new.html.haml
.modal-header
  %button.close{"data-dismiss" => "modal" }
    %span ×
  %h4.modal-title New Todo List
.forms
  = render 'form'

app/views/posts/_post.html.haml
.post{:id => "#{dom_id(post)}"}
  %h2.title= link_to post.title, post
  %p.date
    Published at 
    =time_ago_in_words(post.created_at)
    by
    = post.user.email
  - if user_signed_in?
    .buttons.btn-group.btn-group-xs
      = link_to 'Edit', edit_post_path(post), remote: true , class: "btn btn-default"
      = link_to 'Delete', post_path(post), method: :delete, data: { confirm: "Are you sure?" }, remote: true , class: "btn btn-default"

app/views/posts/_posts.html.haml
- @posts.each do |post|
  =render post

<script type='text/javascript'>
= render(:partial => 'notification', :handlers => [:erb], :formats => [:js])
</script>

app/views/posts/create.js.erb
<% if @post.errors.any? %>
   $( ".error" ).remove();
   <% if @post.errors[:title]%>
      $( "<div class='error'><%= @post.errors[:title].first %> </div>" ).insertAfter( $("#post_title"));
   <% end %>
   <% if @post.errors[:content]%>
      $( "<div class='error'><%= @post.errors[:content].first %> </div>" ).insertAfter( $("#post_content"));
   <% end %>
<% else %>
   $("#modal-window").modal("hide")
   if( $('#posts').length )        
      {$("<%= j(render @post) %>").hide().appendTo('#posts').show().addClass('magictime puffIn'); } 
   else { 
    var post = $('<%= j(render :file => 'posts/show') %>').hide();
    $('#post_contents').replaceWith(post);
    $('#post_contents').show().addClass('magictime spaceInUp')
    window.history.pushState('','',"<%= @post.id %>");
    }
    <%= render 'notification', formats: [:js] %>
<% end %>

app/views/posts/destroy.js.erb
$('#post_<%= @post.id %>').addClass('magictime spaceOutLeft')
setTimeout(function () { 
   $('#post_<%= @post.id %>').remove();
}, 800);

<%= render 'notification', formats: [:js] %>

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

app/views/posts/edit.js.erb
$("#modal-window").html("<%= escape_javascript(render 'form') %>")
$("#modal-window").modal("show")

app/views/posts/index.html.haml
#posts
  = render "posts"

app/views/posts/new.js.erb
$("#modal-window").html("<%= escape_javascript(render 'form') %>")
$("#modal-window").modal("show")

app/views/posts/show.html.haml
#post_contents
  %h1= @post.title
  %p= @post.content

  #comments
    %h2= @post.comments.count
    = render @post.comments

    %h3#comment_form_header Reply to thread
    = render "comments/form"

 

app/views/posts/update.js.erb
$("#modal-window").modal("hide") 
$("#post_<%= @post.id %>").replaceWith("<%= escape_javascript(render partial: 'post', locals: { post: @post } ) %>"); 

<%= render 'notification', formats: [:js] %>