config/routes.rb
Rails.application.routes.draw do
   resources :posts do
      resources :comments
   end
   match 'remote_sign_up', to: 'remote_content#remote_sign_up', via: [:get]
   match 'remote_sign_in', to: 'remote_content#remote_sign_in', via: [:get]

   devise_for :users, :controllers => {registrations: 'registrations', sessions: 'sessions'}

   root "posts#index"

end

app/controllers/remote_content_controller.rb
class RemoteContentController < ApplicationController
   def remote_sign_in
       respond_to do |format|
         format.html {redirect_to new_user_session_path}
         format.js {render 'remote_sign_in'}
       end
   end

   def remote_sign_up
       respond_to do |format|
         format.html {redirect_to new_user_registration_path}
         format.js {render 'remote_sign_up'}
       end
   end
end

app/views/remote_content/_remote_sign_in.html.haml
#sign_in_modal.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"}
          %i.fa.fa-times-circle
        %h4#SignInModal.modal-title Log In
        %p Add your credential for log in
      = simple_form_for(resource, :as => resource_name, :url => session_path(resource_name), :remote => true, :format => :js,  :html => {:class => "form-signin"}) do |f|
        .modal-body
          //= f.error_notification
          = f.input :email, :autofocus => true, :label => false, :input_html => {:class => 'form-control'}, :placeholder => "E-mail"
          = f.input :password, :label => false, :input_html => {:class => 'form-control'}, :placeholder => "Password"
          = f.input :remember_me, as: :boolean if devise_mapping.rememberable?
        .modal-footer
          .form-actions
            %a{ :href => "#", :class => "btn btn-sm", "data-dismiss" => "modal" } Annulla
            = f.button :submit, "Sign in", :class => "btn btn-sm btn-theme"

app/views/remote_content/_remote_sign_up.html.haml
#sign_up_modal.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"}
          %i.fa.fa-times-circle
        %h4#SignInModal.modal-title Create an account
        %p Add your details to create an account
      = simple_form_for(resource, :as => resource_name, :url => registration_path(resource_name), :remote => true, :format => :js,  :html => {:class => "form-signin"}) do |f|
        .modal-body
          //= f.error_notification
          = f.input :email, :autofocus => true, :label => false, :input_html => {:class => 'form-control'}, :placeholder => "E-mail"
          = f.input :password, :label => false, :input_html => {:class => 'form-control'}, :placeholder => "Password"
          = f.input :password_confirmation, :label => false, :input_html => {:class => 'form-control'}, :placeholder => "Confirm password"
          = link_to "Hai già un account?", new_user_session_path
          = link_to "Hai dimenticato la tua password?", new_user_password_path
        .modal-footer
          .form-actions
            %a{ :href => "#", :class => "btn btn-sm", "data-dismiss" => "modal" } Annulla
            = f.button :submit, "Sign up", :class => "btn btn-sm btn-theme"

app/views/remote_content/devise_errors.js.erb
<%= render 'notification', formats: [:js] %>

app/views/remote_content/devise_success_sign_in.js.erb
$('.modal').modal('hide')

<%= render 'notification', formats: [:js] %>

<% flash.clear %>

window.location.href = "<%= escape_javascript(@after_sign_in_path) %>";

app/views/remote_content/devise_success_sign_up.js.erb
$('.modal').modal('hide')

<%= render 'notification', formats: [:js] %>

app/views/remote_content/remote_sign_in.js.erb
if($('#sign_up_modal').length > 0) {
  $("#sign_up_modal").remove();
}

if($('#sign_in_modal').length > 0) {
  $("#sign_in_modal").modal();
}
else {
  $("body").prepend("<%= escape_javascript(render "remote_sign_in", :formats => [:html]) %>");
  $("#sign_in_modal").modal();
}

app/views/remote_content/remote_sign_up.js.erb
if($('#sign_in_modal').length > 0) {
  $("#sign_in_modal").remove();
}

if($('#sign_up_modal').length > 0) {
  $("#sign_up_modal").modal();
}
else {
  $("body").prepend("<%= escape_javascript(render "remote_sign_up", :formats => [:html]) %>");
  $("#sign_up_modal").modal();
}