config/routes.rb
Rails.application.routes.draw do
   resources :posts do
      resources :comments
   end
   match 'remote_sign_up', to: 'remote_content#remote_sign_up', via: [:get]
   match 'remote_sign_in', to: 'remote_content#remote_sign_in', via: [:get]

   devise_for :users, :controllers => {registrations: 'registrations', sessions: 'sessions'}

   root "posts#index"

end

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default
  / Brand and toggle get grouped for better mobile display
  .navbar-header
    %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    =link_to "Sphynx Rails Forum", posts_path, class: 'navbar-brand'
  / Collect the nav links, forms, and other content for toggling
  #bs-example-navbar-collapse-1.collapse.navbar-collapse
    %ul.nav.navbar-nav.navbar-right
      - if user_signed_in?
        %li= link_to "New Post", new_post_path, :remote => true
        %li= link_to "Account", edit_user_registration_path            
        %li= link_to "Sign Out", destroy_user_session_path, method: :delete
      - else
        %li= link_to "Sign Up", remote_sign_up_path, :remote => true, class: "active"
        %li= link_to "Sign In",  remote_sign_in_path, :remote => true, class: "active"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Forum
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    %link{ rel: "stylesheet", href: "http://fonts.googleapis.com/css?family=Lato:300,400,700", type: "text/css"}
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container
      .row
        .col-md-10.col-md-offset-1
          = render 'layouts/header'

    .container
      #modal-window.modal.fade{:role => "dialog"}
      .row
        .col-md-8.col-md-offset-2
          - unless request.xhr?
            #wrap_error
              #flash
                - flash.each do |type, message|
                  .alert.alert-dismissable{ :class => twitterized_type(type) }
                    %button.close{"data-dismiss" => "alert", "aria-hidden" => "true"} ×
                    %p= message
          = yield 